import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextTail with TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-screen w-screen place-content-center">
        <h1 className="text-5xl font-bold">Welcome to NextTail</h1>
        <p className="mt-2 text-center">
          Get started by editing&nbsp;
          <code className="underline">src/pages/index.tsx</code>
        </p>
      </main>
    </>
  );
}
